### ISSUE TITLE
GraphNodes UI improvements

### ISSUE THREAD

**Issue by HungryProton** [HungryProton/concept_graph#72]
- Allow local edition of Vector2 and Vector3
- Improve the Spinbox style
- Enforce nodes to always use as little amount of space as possible

**Comment by HungryProton** [comment]
Added in 5497de3dfcd5a93e4fb0b73e006bac5247c053b3

**Comment by BryceBubbles** [comment]
Woh this is going to take some getting used to.

Couple of requests:
- A scalar input next to an output with a label, will cut off the inputs label. Setting the input as index 1 instead of 0 forces it to the next line, but then the last input is hidden off the bottom.
- Could vectors be inline by default (pretty please), with the label above like now, but with it's background the same as the spinbox? Even with a Vector3 there should be enough space to comfortably show a Vector3(9999, 9999, 9999) and how often do you need to enter more than that?
- Adding large number pushes the spinbox outside the node until you hit enter, then it resizes the node box. Removing the large number doesn't shrink the node back down.

**Comment by HungryProton** [comment]
Everything is based on Blender's UI, the built-in Godot spinbox is really unpractical to work with.

+ Right, there's an alignment issue there so the required minimum space is not calculated properly, will try to fix today
![image](https://user-images.githubusercontent.com/52043844/83970587-bb79a280-a8d6-11ea-9184-669e05a0ccc7.png)
+ I don't really like how large they make the node when vectors are inlined but now I can add options quite easily so both could be available.
+ Should be an easy fix

**Comment by HungryProton** [comment]
Should be partially fixed in cc36840ad19207342e600505f1d17aee4a7f05ff

+ The first point requires to rethink the whole layout of graphnodes so I just increased the minimum size based on the largest output label for now. I'll work on a proper fix once I'll be done with more pressing issues
+ There's now an option in the `Project Settings` to inline vectors. I can add some spacing or try to shrink them down even more if you'd like.
![image](https://user-images.githubusercontent.com/52043844/83974664-567e7680-a8ef-11ea-9c68-520e94b95240.png)
+ Last point should be fixed but really large numbers are not properly displayed. Should not be an issue in most cases since it only happens with 10+ digits.

**Comment by BryceBubbles** [comment]
That's awesome! The only problem with a global setting might be that switching it could mean some nodes need to be moved around. The ultimate would be a per-node toggle next to the X button, but I'm super happy with this for now.

**Two aesthetic requests that would be nice:**
- Can we make the graph grid size default to 25 so input connects can be lined up easier?
- And to go with this, Is there a way to align the Vector2/3 connection dot with it's label?

**Comment by HungryProton** [comment]
+ I guess per node toggle could be an option for later, so you could switch between inline, not inline and default, but I guess its fine for now.
+ Good point
+ Sadly the GraphNode class doesn't expose a way to move the socket around, expect on the x axis.
